# basic options
title: romvek // Labs
author: Me
email: none@yourbusiness.com
twitter_username: drivenbymetal
github_username: romvek
description: Documenting my journey in system administration, automation, and cybersecurity through hands-on labs and projects.

# Build Options
markdown: kramdown
theme: jekyll-theme-cayman
